<a href="https://colab.research.google.com/github/Joseph-Munyenze/-Electronics-marketting-/blob/main/DCG_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PYTHON COLLECTION
Python collection consists of the  structured data containers which are used to store variables
Examples of the python collection are

1.   List
2.   Tuple
3.   Arrays
4.   Dictonaries

In [ ]:
#List
fruits=["apple","banana","cherry"]
print(fruits)

['apple', 'banana', 'cherry']


In [ ]:
# prompt: write dictionart exampls

# Dictionaries
# Dictionaries are used to store data values in key:value pairs.
# A dictionary is a collection which is ordered*, changeable and do not allow duplicates.

# Create and print a dictionary:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

# Accessing Items
# You can access the items of a dictionary by referring to its key name, inside square brackets:
x = thisdict["model"]
print(x)

# There is also a method called get() that will give you the same result:
x = thisdict.get("model")
print(x)

# Change Values
# You can change the value of a specific item by referring to its key name:
thisdict["year"] = 2018
print(thisdict)


# Loop Through a Dictionary
# You can loop through a dictionary by using a for loop.
# When looping through a dictionary, the return value are the keys of the dictionary, but there are methods to return the values as well.

# Print all key names in the dictionary, one by one:
for x in thisdict:
  print(x)

# Print all values in the dictionary, one by one:
for x in thisdict:
  print(thisdict[x])

# You can also use the values() method to return values of a dictionary:
for x in thisdict.values():
  print(x)

# Loop through both keys and values, by using the items() method:
for x, y in thisdict.items():
  print(x, y)


# Check if Key Exists
# To determine if a specified key is present in a dictionary use the in keyword:
if "model" in thisdict:
  print("Yes, 'model' is one of the keys in the thisdict dictionary")


# Dictionary Length
# To determine how many items (key-value pairs) a dictionary has, use the len() method.
print(len(thisdict))


# Adding Items
# Adding an item to the dictionary is done by using a new index key and assigning a value to it:
thisdict["color"] = "red"
print(thisdict)

# Removing Items
# There are several methods to remove items from a dictionary:
# The pop() method removes the item with the specified key name:
thisdict.pop("model")
print(thisdict)

# The popitem() method removes the last inserted item (in versions before 3.7, a random item is removed instead):
thisdict.popitem()
print(thisdict)

# The del keyword removes the item with the specified key name:
del thisdict["year"]
print(thisdict)

# The del keyword can also delete the dictionary completely:
# del thisdict
# print(thisdict) #this will cause an error because "thisdict" no longer exists.


# The clear() method empties the dictionary:
thisdict.clear()
print(thisdict)


# Copy a Dictionary
# You cannot copy a dictionary simply by typing dict2 = dict1, because: dict2 will only be a reference to dict1, and changes made in dict1 will automatically also be made in dict2.

# There are ways to make a copy, one way is to use the built-in Dictionary method copy().
mydict = thisdict.copy()
print(mydict)

# Another way to make a copy is to use the built-in function dict().
mydict = dict(thisdict)
print(mydict)

# Nested Dictionaries
# A dictionary can contain dictionaries, this is called nested dictionaries.
myfamily = {
  "child1" : {
    "name" : "Emil",
    "year" : 2004
  },
  "child2" : {
    "name" : "Tobias",
    "year" : 2007
  },
  "child3" : {
    "name" : "Linus",
    "year" : 2011
  }
}

print(myfamily)

# Or, if you want to add three dictionaries into a new dictionary:
child1 = {
  "name" : "Emil",
  "year" : 2004
}
child2 = {
  "name" : "Tobias",
  "year" : 2007
}
child3 = {
  "name" : "Linus",
  "year" : 2011
}

myfamily = {
  "child1" : child1,
  "child2" : child2,
  "child3" : child3
}

myfamily


{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
Mustang
Mustang
{'brand': 'Ford', 'model': 'Mustang', 'year': 2018}
brand
model
year
Ford
Mustang
2018
Ford
Mustang
2018
brand Ford
model Mustang
year 2018
Yes, 'model' is one of the keys in the thisdict dictionary
3
{'brand': 'Ford', 'model': 'Mustang', 'year': 2018, 'color': 'red'}
{'brand': 'Ford', 'year': 2018, 'color': 'red'}
{'brand': 'Ford', 'year': 2018}
{'brand': 'Ford'}
{}
{}
{}
{'child1': {'name': 'Emil', 'year': 2004}, 'child2': {'name': 'Tobias', 'year': 2007}, 'child3': {'name': 'Linus', 'year': 2011}}


{'child1': {'name': 'Emil', 'year': 2004},
 'child2': {'name': 'Tobias', 'year': 2007},
 'child3': {'name': 'Linus', 'year': 2011}}

In [ ]:
# prompt: please make an example also of the tuplr

# Tuple
# Tuples are used to store multiple items in a single variable.
# Tuple items are ordered, unchangeable, and allow duplicate values.
# Tuple items are indexed, the first item has index [0], the second item has index [1] etc.

# Create a Tuple:
thistuple = ("apple", "banana", "cherry")
print(thistuple)

# Access Tuple Items
# You can access tuple items by referring to the index number, inside square brackets:
print(thistuple[1])

# Negative Indexing
# Negative indexing means beginning from the end, -1 refers to the last item, -2 refers to the second last item etc.
print(thistuple[-1])


# Range of Indexes
# You can specify a range of indexes by specifying where to start and where to end the range.
# When specifying a range, the return value will be a new tuple with the specified items.
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[2:5])

# This example returns the items from the beginning to, but NOT included, "kiwi":
print(thistuple[:4])

# This example returns the items from "cherry" and to the end:
print(thistuple[2:])

# Range of Negative Indexes
# Specify negative indexes if you want to start the search from the end of the tuple:
print(thistuple[-4:-1])


# Change Tuple Values
# Once a tuple is created, you cannot change its values. Tuples are unchangeable, or immutable as it also is called.
# But there is a workaround. You can convert the tuple into a list, change the list, and convert the list back into a tuple.
x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)

print(x)

# Loop Through a Tuple
# You can loop through the tuple items by using a for loop.
thistuple = ("apple", "banana", "cherry")
for x in thistuple:
  print(x)

# Check if Item Exists
# To determine if a specified item is present in a tuple use the in keyword:
thistuple = ("apple", "banana", "cherry")
if "apple" in thistuple:
  print("Yes, 'apple' is in the fruits tuple")


# Tuple Length
# To determine how many items a tuple has, use the len() method:
thistuple = ("apple", "banana", "cherry")
print(len(thistuple))


# Add Items
# Once a tuple is created, you cannot add items to it. Tuples are unchangeable.


# Create Tuple With One Item
# To create a tuple with only one item, you have to add a comma after the item, otherwise Python will not recognize it as a tuple.
thistuple = ("apple",)
print(type(thistuple))

#NOT a tuple
thistuple = ("apple")
print(type(thistuple))


# Remove Items
# Tuples are unchangeable, so you cannot remove items from it, but you can delete the tuple completely:
# The del keyword can delete the tuple completely:
thistuple = ("apple", "banana", "cherry")
del thistuple
#print(thistuple) #this will raise an error because the tuple no longer exists


# Join Two Tuples
# To join two or more tuples you can use the + operator:
tuple1 = ("a", "b" , "c")
tuple2 = (1, 2, 3)

tuple3 = tuple1 + tuple2
print(tuple3)


# The tuple() Constructor
# It is also possible to use the tuple() constructor to make a tuple.
thistuple = tuple(("apple", "banana", "cherry")) # note the double round-brackets
thistuple

('apple', 'banana', 'cherry')
banana
cherry
('cherry', 'orange', 'kiwi')
('apple', 'banana', 'cherry', 'orange')
('cherry', 'orange', 'kiwi', 'melon', 'mango')
('orange', 'kiwi', 'melon')
('apple', 'kiwi', 'cherry')
apple
banana
cherry
Yes, 'apple' is in the fruits tuple
3
<class 'tuple'>
<class 'str'>
('a', 'b', 'c', 1, 2, 3)


('apple', 'banana', 'cherry')

In [ ]:
# prompt: create for arrays

# Arrays in Python
# Python does not have built-in support for arrays, but Python Lists can be used instead.
# However, to work with arrays, you will have to import a library, like the NumPy library.

import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

print(arr)

# Accessing elements in an array
print("The first element of the array is: ", arr[0])
print("The last element of the array is: ", arr[-1])

# Array Slicing: Accessing a range of elements in an array
print(arr[1:4])

# Changing elements in an array
arr[0] = 10
print(arr)

# Array properties
print(arr.dtype)  # Data type of the elements
print(arr.shape)  # Dimensions of the array

# Multi-dimensional arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

print(arr_2d.shape) # dimensions of the array
print(arr_2d[0, 0]) #access element at row 0, column 0

# Array operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)
print(arr1 * arr2)


# Array functions
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

# Other array methods
# append: adds an element to the end of the array
# insert: inserts an element at a specific index
# delete: removes an element from the array
# sort: sorts the elements of the array

# Example of append:
my_array = np.array([1, 2, 3])
my_array = np.append(my_array, 4)
my_array

[1 2 3 4 5]
The first element of the array is:  1
The last element of the array is:  5
[2 3 4]
[10  2  3  4  5]
int64
(5,)
[[1 2 3]
 [4 5 6]]
(2, 3)
1
[5 7 9]
[ 4 10 18]
24
4.8
10
2


array([1, 2, 3, 4])

In [1]:
# prompt: write a python class example

import numpy as np

class MyClass:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def greet(self):
        print(f"Hello, my name is {self.name} and I am {self.age} years old.")

# Example usage
my_object = MyClass("Alice", 30)
my_object.greet()

Hello, my name is Alice and I am 30 years old.
